// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function Make(S) {
  var increment = Curry._1(S.add, S.one);
  return {
          increment: increment
        };
}

exports.Make = Make;
/* No side effect */
